# Simple workflow for deploying static content to GitHub Pages
name: Deploy content to Pages

on:
  push:
    branches:
      - "master" # change to the branch you wish to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: bitovi/github-actions-angular-to-github-pages@v1.0.0